<!doctype html>
<html class="no-js" lang="en">

<head>
    <!-- Google tag (gtag.js) This is commented out to disable Google Analytics temporarily. -->

    <!-- <script async src="https://www.googletagmanager.com/gtag/js?id=G-HFJPXGTH23"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-HFJPXGTH23');
    </script> -->


    <meta property="og:title"
        content="<?= isset($page_title) ? $page_title : 'Managed IT Services in Vadodara | Nifty Solutions' ?>">
    <meta property="og:description"
        content="<?= isset($meta_description) ? $meta_description : 'Nifty Solutions provides complete IT solutions in Vadodara — Data backup and Recovery, Enterprise email, firewall, Web Hosting and web development.' ?>">
    <meta property="og:image" content="https://niftysolutions.co.in/public/images/home/banner-desktop.webp">
    <meta property="og:url" content="https://niftysolutions.co.in">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Nifty Solutions">
<meta property="og:locale" content="en_IN">


<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Nifty Solutions | Managed IT Services | Vadodara">
<meta name="twitter:description" content="Nifty Solutions is a leading IT service provider in Vadodara, specializing in data backup, email solutions, firewall security, web development, and more.">
<meta name="twitter:image" content="https://niftysolutions.co.in/public/images/home/banner-desktop.webp">


    <link rel="alternate" hreflang="en-in" href="https://niftysolutions.co.in/" />

<!-- Organisation Schema  -->
<script type="application/ld+json">
{
 "@context": "https://schema.org",
 "@type": "Organization",
 "name": "Nifty Solutions",
 "url": "https://niftysolutions.co.in",
 "logo": "https://niftysolutions.co.in/public/images/logo-black.webp",
 "foundingDate": "1999",
 "address": {
   "@type": "PostalAddress",
   "addressLocality": "Vadodara",
   "addressRegion": "Gujarat",
   "addressCountry": "India"
 },
 "sameAs": [
    "https://www.instagram.com/niftysolutions_it/",
    "https://www.linkedin.com/company/nifty-solutions/"
  ],
 "contactPoint": {
   "@type": "ContactPoint",
   "telephone": "+91-9825412230",
   "contactType": "customer service"
 }
}
</script>


<!-- LocalBusiness Schema  -->
    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "name": "Nifty Solutions",
  "image": "https://niftysolutions.co.in/public/images/logo-black.webp",
  "logo": "https://niftysolutions.co.in/public/images/logo-black.webp",
  "url": "https://niftysolutions.co.in",
  "telephone": "+91-9825412230",
  "email": "sales@niftysolutions.co.in",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "1109, Nilamber Triumph, Nilamber Circle, Gotri-Vasna Road",
    "addressLocality": "Vadodara",
    "addressRegion": "Gujarat",
    "postalCode": "390021",
    "addressCountry": "IN"
  },
  "areaServed": ["Vadodara","Gujarat"],
  "foundingDate": "1999",
  "sameAs": [
    "https://www.instagram.com/niftysolutions_it/",
    "https://www.linkedin.com/company/nifty-solutions/"
  ]
}
</script>

    <!-- Auto-generated canonical tag to avoid duplicate content issues. 
    This uses the current domain and URL path (without query parameters) 
    to set the canonical URL dynamically for each page. -->
    <link rel="canonical"
        href="<?= htmlspecialchars('https://' . $_SERVER['HTTP_HOST'] . strtok($_SERVER['REQUEST_URI'], '?'), ENT_QUOTES, 'UTF-8') ?>" />


        <!-- Autogenerated Schema code for BlogPosts that have information about those posts -->
    <?php
    if (!empty($metadata)): 
        ?>
        <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "BlogPosting"<?php if (!empty($metadata['title'])): ?>,
          "headline": "<?= htmlspecialchars($metadata['title']) ?>"<?php endif; ?><?php if (!empty($metadata['description'])): ?>,
          "description": "<?= htmlspecialchars($metadata['description']) ?>"<?php endif; ?><?php if (!empty($metadata['thumbnail_url'])): ?>,
          "image": "<?= htmlspecialchars($metadata['thumbnail_url']) ?>"<?php endif; ?><?php if (!empty($metadata['author']) || !empty($metadata['author-social-link'])): ?>,
          "author": {
            "@type": "Person"<?php if (!empty($metadata['author'])): ?>,
            "name": "<?= htmlspecialchars($metadata['author']) ?>"<?php endif; ?><?php if (!empty($metadata['author-social-link'])): ?>,
            "url": "<?= htmlspecialchars($metadata['author-social-link']) ?>"<?php endif; ?>
          }<?php endif; ?>,
          "publisher": {
            "@type": "Organization",
            "name": "Nifty Solutions",
            "logo": {
              "@type": "ImageObject",
              "url": "https://niftysolutions.co.in/public/images/logo-white.webp"
            }
          }<?php if (!empty($metadata['date'])): ?>,
          "datePublished": "<?= date('Y-m-d', strtotime($metadata['date'])) ?>"<?php endif; ?>,
          "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": "https://niftysolutions.co.in<?= htmlspecialchars($_SERVER['REQUEST_URI']) ?>"
          }
        }
        </script>
    <?php endif; ?>


    <title><?= isset($page_title) ? $page_title : 'Managed IT Services in Vadodara | Nifty Solutions' ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta name="description"
        content="<?= isset($meta_description) ? $meta_description : 'Nifty Solutions provides complete IT solutions in Vadodara — Data backup and Recovery, Enterprise email, firewall, Web Hosting and web development.' ?>">
    <meta name="robots" content="index, follow">
    <!-- favicon icon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/public/images/apple-touch-icon.webp">
    <link rel="icon" type="image/x-icon" sizes="48x48" href="/favicon.ico">
    <link rel="manifest" href="/public/manifest/site.webmanifest">
    <meta name="theme-color" content="#ffffff">

    <!-- google fonts preconnect -->
    <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- style sheets and font icons -->

    <link rel="stylesheet" href="/public/css/critical.css">
    <!-- Preload and apply CSS files with high priority -->
    <link rel="preload" as="style" href="/public/css/vendors.min.css" onload="this.onload=null;this.rel='stylesheet'">
    <link rel="preload" as="style" href="/public/css/icon.min.css" onload="this.onload=null;this.rel='stylesheet'">
    <link rel="preload" as="style" href="/public/css/responsive.min.css"
        onload="this.onload=null;this.rel='stylesheet'">
    <link rel="preload" as="style" href="/public/css/style.min.css" onload="this.onload=null;this.rel='stylesheet'">
    <link rel="preload" as="style" href="/public/css/custom.css" onload="this.onload=null;this.rel='stylesheet'">
    <!-- <link rel="stylesheet" href="/public/css/style.min.css"> -->
    <!-- <link rel="stylesheet" href="/public/css/custom.css"> -->

    <!-- Fallback for browsers with JavaScript disabled -->
    <noscript>
        <link rel="stylesheet" href="/public/css/vendors.min.css">
    </noscript>
    <noscript>
        <link rel="stylesheet" href="/public/css/icon.min.css">
    </noscript>
    <noscript>
        <link rel="stylesheet" href="/public/css/responsive.min.css">
    </noscript>
    <noscript>
        <link rel="stylesheet" href="/public/css/style.min.css">
    </noscript>
    <noscript>
        <link rel="stylesheet" href="/public/css/custom.css">
    </noscript>
    <!-- <link rel="stylesheet" href="/public/css/demo-it-business.css" /> -->
</head>

<body data-mobile-nav-style="full-screen-menu" data-mobile-nav-bg-color="#252840">
    <?php include_once __DIR__ . '/components/header.php'; ?>

    <main>
        <?= $pageContent ?>
    </main>


    <?php include_once __DIR__ . '/components/footer.php'; ?>
    <?php include_once __DIR__ . '/components/scroll.php'; ?>
    <script type="text/javascript" src="/public/js/jquery.js"></script>
    <script type="text/javascript" src="/public/js/vendors.min.js"></script>
    <script type="text/javascript" src="/public/js/main.js"></script>
    <script type="text/javascript" src="/public/js/custom.js"></script>
    <!-- Additional javascript links can be included here -->
    <?php
    if (isset($additional_javascript_link)) {
        foreach ($additional_javascript_link as $link) {
            echo '<script type="text/javascript" src="' . htmlspecialchars($link, ENT_QUOTES, 'UTF-8') . '"></script>';
        }
    }
    ?>

    <!-- Additional inline scripts can be included here -->
    <?php
    if (isset($additional_inline_script)) {
        foreach ($additional_inline_script as $script) {
            echo '<script type="text/javascript">' . htmlspecialchars($script, ENT_QUOTES, 'UTF-8') . '</script>';
        }
    }
    ?>
</body>

</html>